import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { packageHashFromPath } from "../src/core/hash.js";

// Expected values come from test/fixtures, generated by the server implementation.
const fixtures = JSON.parse(await readFile(new URL("fixtures/fixtures.json", import.meta.url), "utf8")) as {
  files: Record<string, string>;
  ignoredFiles: Record<string, string>;
  packageHash: string;
};

async function writePackage(entries: Record<string, string>): Promise<string> {
  const dir = await mkdtemp(path.join(tmpdir(), "cli-hash-"));
  for (const [rel, content] of Object.entries(entries)) {
    await mkdir(path.dirname(path.join(dir, rel)), { recursive: true });
    await writeFile(path.join(dir, rel), content);
  }
  return dir;
}

describe("packageHashFromPath", () => {
  it("matches the server package hash", async () => {
    const { hash } = await packageHashFromPath(await writePackage(fixtures.files));
    expect(hash).toBe(fixtures.packageHash);
  });

  it("ignores .DS_Store and __MACOSX", async () => {
    const { hash, manifest } = await packageHashFromPath(await writePackage({ ...fixtures.files, ...fixtures.ignoredFiles }));
    expect(hash).toBe(fixtures.packageHash);
    expect(Object.keys(manifest)).toHaveLength(Object.keys(fixtures.files).length);
  });
});
